# Generated by Django 5.2.3 on 2025-06-26 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='EMPRESTADO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_realizados', to='biblioteca.funcionario')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='biblioteca.leitor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='biblioteca.livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
